// frontend/medicine-buddy-react/src/components/features/register/Register.tsx
import { FC, useState } from "react";
import { Card, Button, Alert } from "react-bootstrap";
import { Form } from "react-router";

const Register:FC = () => {
    const [formData, setFormData] = useState({
        firstName: "",
        lastName: "",
        passwordEncrypted: "",
        age: "",
        height: "",
        weight: "",
      } as any);
    
      const [errors, setErrors] = useState({});
      const [isSubmitting, setIsSubmitting] = useState(false);
      const [successMessage, setSuccessMessage] = useState("");
      const [errorMessage, setErrorMessage] = useState("");
    
      const validate = () => {
        const newErrors = {} as any;
        if (!formData.firstName || formData.firstName.length < 2)
          newErrors.firstName = "First Name must be at least 2 characters.";
        if (!formData.lastName || formData.lastName.length < 2)
          newErrors.lastName = "Last Name must be at least 2 characters.";
        if (!formData.passwordEncrypted || formData.passwordEncrypted.length < 6)
          newErrors.passwordEncrypted = "Password must be at least 6 characters.";
        if (!formData.age || formData.age < 1 || formData.age > 150)
          newErrors.age = "Age must be between 1 and 150.";
        if (!formData.height || formData.height < 30 || formData.height > 250)
          newErrors.height = "Height must be between 30 and 250 cm.";
        if (!formData.weight || formData.weight < 10 || formData.weight > 300)
          newErrors.weight = "Weight must be between 10 and 300 kg.";
    
        return newErrors;
      };
    
      const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData((prev) => ({ ...prev, [name]: value }));
      };
    
      const handleSubmit = async (e) => {
        e.preventDefault();
        setSuccessMessage("");
        setErrorMessage("");
        const validationErrors = validate();
    
        if (Object.keys(validationErrors).length > 0) {
          setErrors(validationErrors);
          return;
        }
    
        setIsSubmitting(true);
        setErrors({});
        try {
          const res = await fetch("/api/register", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(formData),
          });
    
          const result = await res.json();
    
          if (res.ok) {
            setSuccessMessage(`Registration Success for Username: ${result.model}`);
            setFormData({
              firstName: "",
              lastName: "",
              passwordEncrypted: "",
              age: "",
              height: "",
              weight: "",
            });
          } else {
            setErrorMessage("Registration failed. Please try again.");
          }
        } catch (error) {
          setErrorMessage("Something went wrong.");
        } finally {
          setIsSubmitting(false);
        }
      };
    
      const handleGoToLogin = () => {
        window.location.href = "/auth";
      };
    
      return (
        <div className="container mt-5">
          <div className="row justify-content-center">
            <div className="col-md-6">
              <Card className="shadow-lg">
                <Card.Body>
                  <h3 className="text-center text-primary">Register</h3>
                  <Form onSubmit={handleSubmit}>
                    {["firstName", "lastName", "passwordEncrypted", "age", "height", "weight"].map((field) => (
                      <Form.Group className="mb-3" key={field}>
                        <Form.Label>
                          {field === "passwordEncrypted"
                            ? "Password"
                            : field.charAt(0).toUpperCase() + field.slice(1)}
                        </Form.Label>
                        <Form.Control
                          type={field === "passwordEncrypted" ? "password" : field === "age" || field === "height" || field === "weight" ? "number" : "text"}
                          name={field}
                          value={formData[field]}
                          onChange={handleChange}
                          isInvalid={!!errors[field]}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors[field]}
                        </Form.Control.Feedback>
                      </Form.Group>
                    ))}
    
                    <div className="d-flex justify-content-between">
                      <Button
                        type="submit"
                        variant="primary"
                        className="w-50 me-1"
                        disabled={isSubmitting}
                      >
                        {!isSubmitting ? "Register" : <span className="spinner-border spinner-border-sm" />}
                      </Button>
                      <Button
                        variant="outline-secondary"
                        className="w-50"
                        disabled={isSubmitting}
                        onClick={handleGoToLogin}
                      >
                        {!isSubmitting ? "Go to Login" : <span className="spinner-border spinner-border-sm" />}
                      </Button>
                    </div>
    
                    {successMessage && <Alert variant="success" className="mt-3">{successMessage}</Alert>}
                    {errorMessage && <Alert variant="danger" className="mt-3">{errorMessage}</Alert>}
                  </Form>
                </Card.Body>
              </Card>
            </div>
          </div>
        </div>
      );
}

export default Register;

// frontend/medicine-buddy-web-ng/src/app/features/register/register.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { HttpService } from 'src/app/core/services/http.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
  registerForm: FormGroup;
  isSubmitting = false;
  successMessage = '';
  errorMessage = '';
  userName = ""

  constructor(private fb: FormBuilder, private httpService: HttpService, private router: Router) {
    this.registerForm = this.fb.group({
      firstName: ['', [Validators.required, Validators.minLength(2)]],
      lastName: ['', [Validators.required, Validators.minLength(2)]],
      passwordEncrypted: ['', [Validators.required, Validators.minLength(2)]],
      age: ['', [Validators.required, Validators.min(0), Validators.max(100)]],
      height: ['', [Validators.required, Validators.min(0), Validators.max(250)]],
      weight: ['', [Validators.required, Validators.min(0), Validators.max(300)]],
    });
  }

  onSubmit() {
    console.log(this.registerForm.value);
    
    if (this.registerForm.invalid) {
      return;
    }

    this.isSubmitting = true;
    this.successMessage = '';
    this.errorMessage = '';

    this.httpService.registerUser(this.registerForm.value).subscribe({
      next: (response) => {
        this.successMessage = `Registration Success for Username: ${response.model}`;
        this.registerForm.reset();
      },
      error: (error) => {
        this.errorMessage = 'Registration failed. Please try again.';
      },
      complete: () => {
        this.isSubmitting = false;
      }
    });
  }

  handleOnClickGotoLogin() : void {
    this.router.navigate(['/auth'])
  }
}
<div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card shadow-lg">
          <div class="card-body">
            <h3 class="card-title text-center text-primary">Register</h3>
  
            <form [formGroup]="registerForm" (ngSubmit)="onSubmit()">
              <div class="form-group mb-3">
                <label for="firstName">First Name</label>
                <input type="text" id="firstName" class="form-control" formControlName="firstName">
                <div *ngIf="registerForm.controls['firstName'].invalid && registerForm.controls['firstName'].touched" class="text-danger">
                  First Name is required and must be at least 2 characters.
                </div>
              </div>
  
              <div class="form-group mb-3">
                <label for="lastName">Last Name</label>
                <input type="text" id="lastName" class="form-control" formControlName="lastName">
                <div *ngIf="registerForm.controls['lastName'].invalid && registerForm.controls['lastName'].touched" class="text-danger">
                  Last Name is required and must be at least 2 characters.
                </div>
              </div>
  
              <div class="form-group mb-3">
                <label for="passwordEncrypted">Password</label>
                <input type="password" id="passwordEncrypted" class="form-control" formControlName="passwordEncrypted">
                <div *ngIf="registerForm.controls['passwordEncrypted'].invalid && registerForm.controls['passwordEncrypted'].touched" class="text-danger">
                  Password must be at least 6 characters.
                </div>
              </div>
  
              <div class="form-group mb-3">
                <label for="age">Age</label>
                <input type="number" id="age" class="form-control" formControlName="age">
                <div *ngIf="registerForm.controls['age'].invalid && registerForm.controls['age.touched']" class="text-danger">
                  Age must be between 1 and 150.
                </div>
              </div>
  
              <div class="form-group mb-3">
                <label for="height">Height (cm)</label>
                <input type="number" id="height" class="form-control" formControlName="height">
                <div *ngIf="registerForm.controls['height'].invalid && registerForm.controls['height.touched']" class="text-danger">
                  Height must be between 30 and 250 cm.
                </div>
              </div>
  
              <div class="form-group mb-3">
                <label for="weight">Weight (kg)</label>
                <input type="number" id="weight" class="form-control" formControlName="weight">
                <div *ngIf="registerForm.controls['weight'].invalid && registerForm.controls['weight.touched']" class="text-danger">
                  Weight must be between 10 and 300 kg.
                </div>
              </div>
              <div class="d-flex justify-content-between">
                <button type="submit" class="btn btn-primary mr-1 w-50" [disabled]="isSubmitting">
                    <span *ngIf="!isSubmitting">Register</span>
                    <span *ngIf="isSubmitting" class="spinner-border spinner-border-sm"></span>
                </button>
                <button type="submit" class="btn btn-outline-secondary w-50" [disabled]="isSubmitting"  (click)="handleOnClickGotoLogin()">
                    <span *ngIf="!isSubmitting">Goto Login</span>
                    <span *ngIf="isSubmitting" class="spinner-border spinner-border-sm"></span>
                </button>
            </div>

              <div *ngIf="successMessage" class="alert alert-success mt-3">
                {{ successMessage }}
              </div>
              <div *ngIf="errorMessage" class="alert alert-danger mt-3">
                {{ errorMessage }}
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
